name: chatz
description: A new Flutter project.



publish_to: 'none' 











version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  google_sign_in: ^5.2.4
  shared_preferences: ^2.0.13
  random_string: ^2.3.1
  cloud_firestore: ^3.1.10
  flutter_automation: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^1.0.0





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
